name: First workflow
on: workflow_dispatch
jobs: 
  print-github:
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
          run: |
           echo "Repository name: $GITHUB_REPOSITORY" 
           echo "Branch or tag reference: $GITHUB_REF"
           echo "Commit SHA: $GITHUB_SHA"